name: Fifth Workflow
on: 
  issues:
    types: [edited, deleted]
  pull_request:
    types: [assigned, closed]

jobs:
    show-commit-hash-and-directory:
        runs-on: ubuntu-latest
        steps:
            - name: Show Commit Hash
              run: |
                echo "Commit Hash: $GITHUB_SHA"
                echo "Repository: $GITHUB_REF"