name: Seventh Workflow
# run-name: This is 7th Workflow
on: push
env: 
  MY_ENV_VAR: my_value 1

jobs:
  my_job:
    env:
        LOCAL_VAR: local_value 1
    runs-on: ubuntu-latest
    steps:
    - name: show variables
      run: |
        echo "MY GLOBAL VAR: $MY_ENV_VAR"
        echo "MY LOCAL VAR: $LOCAL_VAR"
  second_job:
    env:
        LOCAL_VAR: local_value 222222
    runs-on: ubuntu-latest
    steps:
    - name: show variables
      run: |
        echo "MY GLOBAL VAR: $MY_ENV_VAR"
        echo "MY LOCAL VAR: $LOCAL_VAR"
  third_job:
    needs: [second_job, my_job]
    env:
        LOCAL_VAR: local_value 333333
    runs-on: ubuntu-latest
    steps:
    - name: show variables
      run: |
        echo "MY GLOBAL VAR: $MY_ENV_VAR"
        echo "MY LOCAL VAR: ${{ env.LOCAL_VAR }}"
